accuracy: 1.0
algorithm: Crow Search Algorithm
all_features:
- Region_Encoded
- District_Encoded
- Actual(mm)
- Normal(mm)
- '% Dep.'
- Rainfall_Health_Score
classes:
- Deficient
- Excess
- Normal
project_name: Rainfall Deficiency Prediction using CSA
selected_features:
- '% Dep.'
- Rainfall_Health_Score
total_records: 33
